### ISSUE TITLE
Oban Web - support bulk actions on filtered jobs

### ISSUE THREAD

**Issue by up2jj** [oban-bg/oban#1104]
Bulk actions in Oban Web work based on the selected items. We recently struggled with a situation where the worker uniqueness settings were not correct and there were a lot of jobs arriving in the queue with the same parameters. We had to delete jobs cyclically via a manual, hand-crafted SQL query.

In addition to being able to operate on selected items, the interface should also allow actions on all filtered jobs - such as cancelling all jobs - without having to select them.

**Comment by sorentwo** [comment]
You're not the first to request this feature and it's definitely missing from the interface. It's on the list for Web v2.11

**Comment by sorentwo** [comment]
> BTW, is it safe to delete rows in oban_jobs manually? 

It depends on what the jobs are and if the side-effect of deleting them would matter. The primary purpose of events for `cancel_job` and `cancel_all_jobs` is for distributed process killing, batch callbacks, etc.

**Comment by sorentwo** [comment]
<img width="1153" alt="Screenshot 2024-12-05 at 19 57 05" src="https://github.com/user-attachments/assets/bd4f40d4-34a1-4280-b8a2-a34d5899b301">

Coming in Web v2.11
