### ISSUE TITLE
DynamicCron.insert breaks scheduling guarantees

### ISSUE THREAD

**Issue by ftes** [oban-bg/oban#1156]
### Environment
- `oban 2.18.3`
- `oban_pro 1.4.13`
- postgres `13`
- elixir `1.17.3`, erlang `27.1`

### Current Behavior

Updating an existing cron expression via `DynamicCron.insert` can lead to that job being immediately re-run, as DynamicCron thinks the last run was missed.

### Expected Behavior

Either
1. `oban_crons.insertions` should be reset when updating the expression via `DynamicCron.insert`, just like it is reset when updating via `DynamicCron.update`
2. or the docs should clearly state this is not supported

Right now the docs only state
> it is better to use `update/2` to make targeted updates

**Comment by sorentwo** [comment]
Thanks for the report and an excellent discovery. This is fixed on main, and we'll also backport to v1.14 for the next patch release.
