### ISSUE TITLE
Oban Web UI throws 500s for some structured job results

### ISSUE THREAD

**Issue by connorjacobsen** [oban-bg/oban#1157]
### Environment

- Oban Version
  - Oban: `2.18.3`
  - Pro: `1.4.13`
  - Web: `2.10.5`
- PostgreSQL Version: `PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit`
- Elixir & Erlang/OTP Versions (`elixir --version`)
  - Elixir: `1.17.2`
  - OTP: `27.0.1`

### Current Behavior

When using structured jobs, I am sometimes running into certain jobs that cause the Oban Web UI to throw Internal Server Errors when going to the job detail view. The return values of these jobs are all of the form `{:ok, map()}` (the data itself is just `map()`). Unfortunately I cannot post the raw objects for security reasons (but happy to include map shape and keys if helpful), but it's basically just a result JSON blob from an API call that I am storing. No functions or anything I would imagine to be sketchy or unsafe.

Stacktrace:
```
ArgumentError: errors were found at the given arguments:

  * 1st argument: invalid or unsafe external representation of a term

  Module "erlang", in :erlang.binary_to_term/2
  File "lib/oban/web/resolver.ex", line 378, in Oban.Web.Resolver.decode_recorded/2
  File "lib/oban/web/resolver.ex", line 390, in Oban.Web.Resolver.format_recorded/2
  File "lib/oban/web/live/jobs/detail_component.ex", line 188, in anonymous fn/2 in Oban.Web.Jobs.DetailComponent.render/1
  File "lib/phoenix_live_view/diff.ex", line 391, in Phoenix.LiveView.Diff.traverse/7
  File "lib/phoenix_live_view/diff.ex", line 532, in anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
  File "lib/enum.ex", line 2531, in Enum."-reduce/3-lists^foldl/2-0-"/3
  File "lib/phoenix_live_view/diff.ex", line 389, in Phoenix.LiveView.Diff.traverse/7
```

If I go find the job in the `oban_jobs` DB table and grab the `return` key from the `meta` column and then run the `Oban.Web.Resolver.decode_recorded` function on the data, it returns an object just fine. Always possible it's running that function on some different piece of data, maybe? What's even weirder is sometimes it renders fine at first but then eventually stops - not sure if there's a pattern or what it is, though.

This happens both for jobs in both the `completed` and `retryable` state.

Obviously, happy to provide more info if there's something you think would be helpful!

### Expected Behavior

I expect the UI to render and show the job detail / result.

**Comment by sorentwo** [comment]
The [decoder defaults](https://oban.pro/docs/web/2.10.5/Oban.Web.Resolver.html#decode_recorded/2) to using the `:safe` option for decoding. That means it won't create unknown atoms, among other safeguards. What's likely happening is the atom in your map doesn't currently exist in the runtime, perhaps because it ran on a separate node.

You can change the decoding behavior in your application using the [format_recorded/2](https://oban.pro/docs/web/2.10.5/Oban.Web.Resolver.html#c:format_recorded/2) callback in a custom resolver. Here's an example that omits the `[:safe]` flag:

```elixir
def format_recorded(recorded, _job) do
  recorded
  |> decode_recorded([])
  |> inspect(pretty: true)
end
```

Check the [resolver](https://oban.pro/docs/web/2.10.5/Oban.Web.Resolver.html#module-usage) docs for more on usage and the other available callbacks.

**Comment by connorjacobsen** [comment]
Thank you! Sorry for not seeing that in the docs.

**Comment by sorentwo** [comment]
No problem at all! It's not especially obvious from the error message and you'd have no way to link that back to Web docs anyhow 🙂
