### ISSUE TITLE
"Batching Jobs for Monitoring" guide doesn't seem to exist

### ISSUE THREAD

**Issue by Munksgaard** [oban-bg/oban#1163]
The [guide on reporting job progress](https://hexdocs.pm/oban/reporting-progress.html#made-possible-by-unlimited-execution) mentions a guide named "Batching Jobs for Monitoring", but I can't seem to find that guide anywhere. Am I missing something? Should there be a link?

**Comment by sorentwo** [comment]
@Munksgaard Thanks for pointing that out!

That was a left over reference from when the guides were blog posts. That post was never transitioned to a guide because it was outdated. Now that section points to batches in Oban Pro instead.
