### ISSUE TITLE
ObanPro DB ConnectionErrors on quick, high(ish) volume of unique jobs

### ISSUE THREAD

**Issue by lamxw2** [oban-bg/oban#1171]
### Precheck

- Do a quick search and make sure the bug has not yet been reported
- For support, favor using the Elixir Forum, Slack, IRC, etc.
- Be friendly and polite!

### Environment

- Oban Version `2.18.3`, Oban Pro `1.5.0-rc.4`
- PostgreSQL Version `15.7`
- Elixir & Erlang/OTP Versions (`elixir --version`) `1.14.5 Erlang/OTP 25`

### Current Behavior
It's me again lol thanks for all the help and really appreciate this libray.

Not sure if this is a bug or not but this would be the closest template for issues I think.

For context:

We are in the middle of migrating our current scheduled queue system based on Supervisors and GenServers to Oban (Pro), with no risk of duplicating "jobs" since if the app dies, the queues stored in GenServer states get wiped.

Since Oban jobs are stored in the db, they don't get wiped (and we don't want to wipe them only to re-insert them since that is inefficient), so we rely on the unique job checks.

This is my `Worker` config
```
  use Oban.Pro.Worker,
    unique: [
      fields: [:args, :worker],
      keys: [:model_id, :model, :scrape_service],
      states: [:available, :executing],
      period: :infinity
    ],
    max_attempts: 1
```
(To address a [previous discussion](https://github.com/oban-bg/oban/issues/1160), it was recommended not to override `fields` and let it check `queues`, unless we schedule it in multiple queues. For this specific `Worker`, we do schedule them in multiple queues.)

Our `DynamicPruner` is set to `max_age` 3 days.
 
Each Oban job is an entity, and these entities are queried from a parent model. I initially tested this on 300+ parents, then later 78 parents. Each parent model can have anywhere between tens to a few thousand entities, but these entities get scheduled very quickly and concurrently. 

To get an estimate on our volume, after **removing** `unique` (to prevent `ConnectionErrors` and test inserts)
- we tested on 78 (less important) parents, it added 54k jobs in 5 minutes.
- tested on 117 (less important) parents, 73.8k jobs in 6 minutes.

Specifying less important as our more important parent models would have a higher quantity of entities overall.

This is the code where I insert the jobs to Oban
```
(request_provider.requests_queue || [])
    |> Enum.map(fn %{model: {model, model_id}} = request ->
      args =
        request
        |> Map.take([:extract_id, :methods_count, :scrape_service])
        |> Map.merge(%{model_id: parse_model_id(model_id), model: model})

      meta = %{retailer_id: request_provider.retailer.id, priority: priority}

      ObanQueue.assign_queue(args, meta)
    end)
    |> Oban.insert_all()
```
--------------------
On to our issue, we frequently experience this error and stacktrace while adding jobs. I assume `find_dupes` is related to the unique check.

![image](https://github.com/user-attachments/assets/90844d52-f787-4497-a7e7-9c48f616e33c)

We observed the long running queries and locks on our phoenix dashboard and noticed that what we think is the unique job check query consistently being a long running query and having multiple locks.

![image](https://github.com/user-attachments/assets/e207b983-1e66-4d90-88a8-d2ce894ca62b)

![image](https://github.com/user-attachments/assets/6cf64aa8-dbbc-426a-9621-de1a2f0489a9)

I didn't manage to screenshot, but I did see some of the query locks exceed 30s.

We removed the `unique` config from our `Worker` and haven't had any db connection errors since.

I've read the Scaling guide on the docs and understand that it's recommended to have a 2nd Repo and dedicated database for high concurrency. However, if the unique job check locks the table frequently for >30s, we're unsure if having a dedicated database would resolve the issue for our use case. 

### Expected Behavior

To be honest, I'm not sure if this is the expected behaviour for Oban Pro for this volume of jobs and that it's due to improper scaling handling on our end, or if currently the unique job check isn't able to handle that volume yet. I guess the expected behaviour would be no timeouts? 🤔

**Comment by sorentwo** [comment]
You're hitting the legacy (and vastly slower) unique path because of missing migrations. Read through the [upgrade guide](https://oban.pro/docs/pro/1.5.0-rc.5/v1-5.html) and run the Pro migrations. That will switch to the new [enhanced unique](https://oban.pro/docs/pro/1.5.0-rc.5/changelog.html#enhanced-unique) mode.

Side note:

Using partial states is discouraged because of errors, snoozing, etc. Consider changing your `states` to `[:available, :scheduled, :executing, :retryable]`

**Comment by sorentwo** [comment]
Will you check whether your `oban_jobs` table has a `uniq_key` column? Also, please check which version is listed under the description for the producers table with `\dt+ oban_producers`

There's a chance the `up` migration didn't take, and you're actually running with the `1.4.0` migration instead.

**Comment by lamxw2** [comment]
> Will you check whether your `oban_jobs` table has a `uniq_key` column? 

It doesn't, I can see that `uniq_key` is saved under meta. 

> Also, please check which version is listed under the description for the producers table with `\dt+ oban_producers`

It is `1.4.0`.  

> There's a chance the `up` migration didn't take, and you're actually running with the `1.4.0` migration instead.

Seems about right then. Thanks
