### ISSUE TITLE
Oban Pro 1.5 rc migration doc mistake

### ISSUE THREAD

**Issue by beerlington** [oban-bg/oban#1172]
I wasn't sure where to report this, but the Oban pro 1.5.0-rc.5 migration [upgrading docs ](https://getoban.pro/docs/pro/1.5.0-rc.5/Oban.Pro.Migration.html#module-upgrading)have a mistake:

```ex
defmodule MyApp.Repo.Migrations.UpgradeObanPro do
  use Ecto.Migration

  def up, do: Oban.Pro.Migrations.up(version: "1.5.0")

  def down, do: Oban.Migrations.down(version: "1.4.0")
end
```

Both `up` and `down` have the wrong module name, and should be:

```ex
defmodule MyApp.Repo.Migrations.UpgradeObanPro do
  use Ecto.Migration

  def up, do: Oban.Pro.Migration.up(version: "1.5.0")

  def down, do: Oban.Pro.Migration.down(version: "1.4.0")
end
```

**Comment by sorentwo** [comment]
Thanks, this was the right place to report it. It's fixed up now.
