### ISSUE TITLE
Support v1.x phoenix_live_view

### ISSUE THREAD

**Issue by kubosuke** [oban-bg/oban#1181]
### Is your feature request related to a problem? Please describe.

we're using oban_web, but once we tried to upgrade our phoenix_liveview_version , it conflicts with oban_web's dependencies as following:

```
Resolving Hex dependencies...
Resolution completed in 0.46s
Because your app depends on oban/oban_web ~> 2.10.4 which depends on phoenix_live_view ~> 0.20, phoenix_live_view ~> 0.20 is required.
So, because your app depends on phoenix_live_view ~> 1.0.0-rc.7, version solving failed.
```

### Describe the Solution You'd Like

Support v1.x phoenix_live_view

**Comment by sorentwo** [comment]
We'll have proper support for liveview when the official v1.0 release is out. There aren't any known incompatibilities, and you can set `override: true` on `phoenix_live_view` to force it.
