### ISSUE TITLE
Oban.Met.Reporter GenServer is terminating due to Postgrex.Error `wrong_object_type`

### ISSUE THREAD

**Issue by nickgnd** [oban-bg/oban#1182]
Hey 👋 
We are happily oban pro users, thanks for the great work.

### Environment

- Oban 2.18.3
- Oban Pro 1.14.3
- Oban Met 0.1.11
- PostgreSQL 15.7
- ecto_sql 3.12.1
- erlang 27.0.1
- elixir 1.17.2-otp-27

### Current Behavior

We updated `oban_met` from v0.1.10 to v0.1.11 2 weeks ago ca. and since then we started to observe these errors in our logs.

```
GenServer {Oban.Registry, {Oban, Oban.Met.Reporter}} terminating **
(Postgrex.Error) ERROR 42809 (wrong_object_type) op ANY/ALL (array) requires array on right side
(ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
(ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
(ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
(ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
(oban_met 0.1.11) lib/oban/met/reporter.ex:174: anonymous fn/3 in Oban.Met.Reporter.checks/1
(ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
(db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
(oban 2.18.3) lib/oban/repo.ex:156: Oban.Repo.transaction/4

Last message: :checkpoint
```

☝️ I don't think we changed anything on our side that could trigger this error. Also the logs do not provide much information apart from this error.

### Expected Behavior

No error.

---

Cheers ✌️

**Comment by sorentwo** [comment]
Thanks for the report. This is fixed on main for oban_met and will be in the next release. Out of curiosity, will you share more about your queues and job counts?

1. Are you using Pro and the Smart engine?
2. How many queues are you running? Would it ever be 0?

**Comment by nickgnd** [comment]
> Are you using Pro and the Smart engine?
Yes

> How many queues are you running? Would it ever be 0?
Looking at the Oban dashboard we have more than 20 queues.

Let me know if you have more specific questions, happy to help ✌️
