### ISSUE TITLE
Swallowed (Postgrex?) exception in Oban.insert_all

### ISSUE THREAD

**Issue by michallepicki** [oban-bg/oban#1186]
### Environment

- Oban Version - 2.18.3 , oban_pro 1.4.13
- PostgreSQL Version - 14.13
- Elixir & Erlang/OTP Versions - Elixir 1.17.2, Erlang 27.0.1
- ecto - 3.12.4
- ecto_sql - 3.12.1
- postgrex - 0.19.2

### Current Behavior

When using `Oban.insert_all` with a very big amount of jobs (around 35k), we've seen this not very helpful error:
```
RuntimeError: operation :rollback is rolling back unexpectedly.

This can happen if `repo.rollback/1` is manually called, which is not supported by `Ecto.Multi`. It can also occur if a nested transaction has rolled back and its error is not bubbled up to the outer multi. Nested transactions are discouraged when using `Ecto.Multi`. Consider flattening out the transaction instead.

  File "lib/ecto/repo/transaction.ex", line 26, in Ecto.Repo.Transaction.transaction/4
  File "lib/oban/repo.ex", line 156, in Oban.Repo.transaction/4
  File "lib/oban/pro/engines/smart.ex", line 733, in anonymous fn/3 in Oban.Pro.Engines.Smart.inner_insert_all/4
  File "lib/enum.ex", line 4353, in Enum.flat_map_list/2
  File "lib/enum.ex", line 4354, in Enum.flat_map_list/2
  File "lib/ecto/adapters/sql.ex", line 1400, in anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
  File "lib/db_connection.ex", line 1756, in DBConnection.run_transaction/4
  File "lib/oban/repo.ex", line 156, in Oban.Repo.transaction/4
``` 

The message says that possibly `Repo.rollback` is mis-used somewhere in oban or oban_pro code? This is a problem because the actual inner issue is not visible anywhere in the exception message or stacktrace, so it's hard to fix. We think for us it was some kind of timeout, possibly a Postgrex exception that was rescued, because we stopped seeing that error after passing `timeout: :infinity` to `insert_all`.

### Expected Behavior

I think maybe the inner exception should be simply re-raised? Or maybe Multi has some other go-to way of handling such errors without manually calling `Repo.rollback`

**Comment by sorentwo** [comment]
This is coming from a timeout in a nested transactions. We'll see if this can be handled differently to expose a better error message.

**Comment by sorentwo** [comment]
This doesn't appear to be an issue in v1.5 (though there's no explicit use `:rollback` anywhere in the Smart engine for v1.4 either). Here's a small test to confirm that a large batch raises a timeout error rather than an obscured rollback:

```elixir
defmodule Foo do
  use Oban.Pro.Worker

  @impl true
  def process(_job), do: :ok
end

Oban.Pro.Repo.start_link()
Oban.start_link(engine: Oban.Pro.Engines.Smart, repo: Oban.Pro.Repo)

1..10_000
|> Stream.map(&Foo.new(%{id: &1}))
|> Oban.insert_all(timeout: 10)
```

Here's the error it raises:

```
21:48:57.869 [error] Postgrex.Protocol (#PID<0.223.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.207.0> timed out because it queued and checked out the connection for longer than 10ms

Client #PID<0.207.0> is still using a connection from owner at location:

    (elixir 1.17.3) lib/map.ex:526: Map.get/2
    (ecto 3.12.1) lib/ecto/changeset.ex:832: Ecto.Changeset.process_param/9
    (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.12.1) lib/ecto/changeset.ex:792: Ecto.Changeset.cast/6
    (oban 2.18.2) lib/oban/job.ex:309: Oban.Job.new/2
    (elixir 1.17.3) src/elixir.erl:386: :elixir.eval_external_handler/3
    (elixir 1.17.3) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
    (elixir 1.17.3) lib/range.ex:538: Enumerable.Range.reduce/5

The connection itself was checked out by #PID<0.207.0> at location:

    (oban 2.18.2) lib/oban/repo.ex:156: Oban.Repo.transaction/4
```
