### ISSUE TITLE
Can't specify prefix option when using Oban.Pro.Testing

### ISSUE THREAD

**Issue by mattnenterprise** [oban-bg/oban#1190]
### Environment

- Oban Version - 2.18.3, Oban Pro any version 1.5.0-rc.1 or greater 
- PostgreSQL Version - 15
- Elixir & Erlang/OTP Versions - Elixir 1.17.3, Erlang 27.1.2

### Current Behavior

Trying to specify the prefix when using `Oban.Pro.Testing` like the following:
```
use Oban.Pro.Testing, repo: MyApp.Repo, prefix: "oban"
```

Always results in the following error when the Oban Pro version is 1.5.0-rc.1 or greater:
```
== Compilation error in file test/my_app/some_test.exs ==
  ** (ArgumentError) unknown keys [:prefix] in [repo: {:__aliases__, [line: 2, counter: {MyApp.SomeTest, 2}, alias: false], [:MyApp, :Repo]}, prefix: "oban"], the allowed keys are: [:repo]
      (elixir 1.17.3) lib/keyword.ex:362: Keyword.validate!/2
      (oban_pro 1.5.0-rc.6) expanding macro: Oban.Pro.Testing.__using__/1
      test/my_app/some_test.exs:2: MyApp.SomeTest (module)
      (elixir 1.17.3) expanding macro: Kernel.use/2
      test/my_app/some_test.exs:2: MyApp.SomeTest (module)
      (my_app 0.1.0) expanding macro: MyApp.DataCase.__using__/1
      test/my_app/some_test.exs:2: MyApp.SomeTest (module)
      (elixir 1.17.3) expanding macro: Kernel.use/2
      test/my_app/some_test.exs:2: MyApp.SomeTest (module)
  [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
  [os_mon] memory supervisor port (memsup): Erlang has closed
```

This looks to originate from a `Keyword.validate!(repo_opts, [:repo])` call in the using macro that only allows the repo option.

### Expected Behavior

The tests compile and run using the prefix defined when using `Oban.Pro.Testing`

**Comment by sorentwo** [comment]
Thanks for the report. Fixed for inclusion in the next RC.
