### ISSUE TITLE
Getting Lifeline working on MySQL

### ISSUE THREAD

**Issue by beerlington** [oban-bg/oban#1198]
The Lifeline module currently relies on using `select` and `update_all` in the same Ecto query, which is not supported on MySQL. 

It is these two lines in particular:

https://github.com/oban-bg/oban/blob/main/lib/oban/plugins/lifeline.ex#L161
https://github.com/oban-bg/oban/blob/main/lib/oban/plugins/lifeline.ex#L170

Is there a reason the `select` part of the query is needed there? If so, is there a workaround that can be used for MySQL?

**Comment by sorentwo** [comment]
@beerlington Please take a look at #1199 🙂

**Comment by beerlington** [comment]
@sorentwo that seems like a great fix, thanks!

Since we'd be switching from Oban Pro's DynamicLifeline to this, what do you recommend to ensure we don't accidentally re-enqueue long running jobs? We have a handful of known workers that can sometimes take 1+ hours. Is there a way to exclude these from the Lifeline?

**Comment by sorentwo** [comment]
> Is there a way to exclude these from the Lifeline?

No, the standard Lifeline is purposefully simple. Please send an email to support@getoban.pro and we'll help you set something up.

**Comment by beerlington** [comment]
@sorentwo I just sent an email.
