### ISSUE TITLE
Support phoenix_live_view 1.0.0 in oban_web

### ISSUE THREAD

**Issue by Ch4s3** [oban-bg/oban#1203]
### Is your feature request related to a problem? Please describe.

We need oban_web to support `phoenix_live_view` 1.0.0. Currently it is locked to 0.20.0.

### Describe the Solution You'd Like

Support for phoenix_live_view 1.0.0.

### Describe Alternatives You've Considered

I don't have an alternative, this is blocking our upgrade.

### Additional Context

We're seeing this when compiling:

```
Because "your app" depends on "oban/oban_web ~> 2.10.5" which depends on "phoenix_live_view ~> 0.20", "phoenix_live_view ~> 0.20" is required.
```

**Comment by sorentwo** [comment]
The upcoming Oban Web v2.11 will officially support LiveView v1.0. Until then there aren't any incompatibilities and you can safely add an `override: true` to force dependency resolution.

```elixir
{:phoenix_live_view, "~> 1.0", override: true}
```

**Comment by Ch4s3** [comment]
I'll keep trying that, but something about our umbrella app isn't respecting the override. Thanks for the update.

**Comment by sorentwo** [comment]
LiveView v1.0 is now supported (required) in [Web v2.10.6](https://oban.pro/releases/web#2.10.6).
