### ISSUE TITLE
CHANGELOG for 2.18.3 is not present in the Markdown file

### ISSUE THREAD

**Issue by AntoineAugusti** [oban-bg/oban#1209]
Hey,

The changes are only listed in the GitHub release and not the Markdown file. Is it standard?

**Comment by sorentwo** [comment]
The changes are on the v2.18 branch, not on main: https://github.com/oban-bg/oban/blob/v2.18/CHANGELOG.md#v2183--2024-09-10.

You can also find them on hexdocs: https://hexdocs.pm/oban/changelog.html#v2-18-3-2024-09-10

**Comment by AntoineAugusti** [comment]
Duh! 🤦 thanks for your quick reply!
